version: '3'

services:
  bookdb:
      image: postgres:10
      volumes:
         - "./book-data:/var/lib/postgresql/data"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 60s
        retries: 3
      environment:
          - POSTGRES_PASSWORD=zeshaadmin
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - bookstore
    ports:
      - '80:80'

  bookstore:
    image: book-store-app:latest
    environment:
      - BOOK_DB_URL=jdbc:postgresql://bookdb:5432/postgres?user=postgres&password=zeshaadmin
      - APPLICATION_SECRET=e3[4XAlEHu8BIA5>8=eXwMjXikTo5Cr<6A2QVbbkCg?9L6IiBdk6q:FxxkWswmsU
    depends_on:
      - bookdb
    restart: on-failure 

volumes:
   book-data:
